"""init schema

Revision ID: 39ca42a59c2f
Revises: 
Create Date: 2026-06-02 14:58:51.269833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39ca42a59c2f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('input', sa.JSON(), nullable=True),
    sa.Column('predicted_price', sa.Integer(), nullable=True),
    sa.Column('range_min', sa.Integer(), nullable=True),
    sa.Column('range_max', sa.Integer(), nullable=True),
    sa.Column('comparables_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scrape_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('seen', sa.Integer(), nullable=True),
    sa.Column('added', sa.Integer(), nullable=True),
    sa.Column('updated', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brand_id', 'name')
    )
    op.create_table('listings',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('otomoto_id', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('mileage_km', sa.Integer(), nullable=True),
    sa.Column('engine_capacity_cm3', sa.Integer(), nullable=True),
    sa.Column('engine_power_hp', sa.Integer(), nullable=True),
    sa.Column('fuel_type', sa.Enum('petrol', 'diesel', 'hybrid', 'phev', 'electric', 'lpg', name='fueltype'), nullable=True),
    sa.Column('gearbox', sa.Enum('manual', 'automatic', name='gearbox'), nullable=True),
    sa.Column('price_pln', sa.Integer(), nullable=True),
    sa.Column('price_raw', sa.Text(), nullable=True),
    sa.Column('currency', sa.Text(), nullable=True),
    sa.Column('accident_free', sa.Boolean(), nullable=True),
    sa.Column('damaged', sa.Boolean(), nullable=True),
    sa.Column('first_owner', sa.Boolean(), nullable=True),
    sa.Column('vat_invoice', sa.Boolean(), nullable=True),
    sa.Column('aso_serviced', sa.Boolean(), nullable=True),
    sa.Column('country_origin', sa.Text(), nullable=True),
    sa.Column('seller_type', sa.Enum('private', 'dealer', name='sellertype'), nullable=True),
    sa.Column('city', sa.Text(), nullable=True),
    sa.Column('voivodeship', sa.Text(), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('otomoto_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('listings')
    op.drop_table('models')
    op.drop_table('scrape_runs')
    op.drop_table('predictions')
    op.drop_table('brands')
    # ### end Alembic commands ###
