"""add indexes to listings

Revision ID: 5315f1f221f6
Revises: 39ca42a59c2f
Create Date: 2026-06-04 20:12:02.414416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5315f1f221f6'
down_revision: Union[str, Sequence[str], None] = '39ca42a59c2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_listings_is_active', 'listings', ['is_active'], unique=False)
    op.create_index('ix_listings_model_year', 'listings', ['model_id', 'year'], unique=False)
    op.create_index('ix_listings_model_year_mileage', 'listings', ['model_id', 'year', 'mileage_km'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_listings_model_year_mileage', table_name='listings')
    op.drop_index('ix_listings_model_year', table_name='listings')
    op.drop_index('ix_listings_is_active', table_name='listings')
    # ### end Alembic commands ###
